name: meu_novo_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0 # Adicione esta linha

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0